services:
  web:
    build: ./fe
    ports:
      - "5002:5002"  
    networks:
      - crypto-net
    depends_on:
      - backend-service

  backend-service:
    build: ./be
    ports:
      - "5001:5001"
    networks:
      - crypto-net
    environment:
      - MYSQL_HOST=mysqldb  
      - DB_PORT=3306
      - MYSQL_USER=root
      - MYSQL_PASSWORD=123456

  mysqldb:
    image: mysql:5.7
    platform: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: crypto_db
    networks:
      - crypto-net

networks:
  crypto-net:
    driver: bridge
      
      